AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  License: Apache-2.0
Description: 'AWS CloudFormation Sample Template EC2InstanceWithSecurityGroup'
Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t3.small
    AllowedValues: [t2.nano, t2.micro, t2.small, t2.medium, t2.large, t2.xlarge, t2.2xlarge,
      t3.nano, t3.micro, t3.small, t3.medium, t3.large, t3.xlarge, t3.2xlarge,
      m4.large, m4.xlarge, m4.2xlarge, m4.4xlarge, m4.10xlarge,
      m5.large, m5.xlarge, m5.2xlarge, m5.4xlarge,
      c5.large, c5.xlarge, c5.2xlarge, c5.4xlarge, c5.9xlarge,
      g3.8xlarge,
      r5.large, r5.xlarge, r5.2xlarge, r5.4xlarge, r3.12xlarge,
      i3.xlarge, i3.2xlarge, i3.4xlarge, i3.8xlarge,
      d2.xlarge, d2.2xlarge, d2.4xlarge, d2.8xlarge]
    ConstraintDescription: must be a valid EC2 instance type.
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
Mappings:
  AmazonLinuxAMI:
    us-east-1:
      AMI: ami-c58c1dd3
    us-east-2:
      AMI: ami-4191b524
    us-west-1:
      AMI: ami-7a85a01a
    us-west-2:
      AMI: ami-4836a428
    ca-central-1:
      AMI: ami-0bd66a6f
    eu-west-1:
      AMI: ami-01ccc867
    eu-west-2:
      AMI: ami-b6daced2
    eu-central-1:
      AMI: ami-b968bad6
    sa-east-1:
      AMI: ami-37cfad5b
    ap-southeast-1:
      AMI: ami-fc5ae39f
    ap-southeast-2:
      AMI: ami-162c2575
    ap-south-1:
      AMI: ami-0cb0e70f44e1a4bb5
    ap-northeast-1:
      AMI: ami-923d12f5
    ap-northeast-2:
      AMI: ami-9d15c7f3
Resources:
  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref 'InstanceType'
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      SecurityGroups: [!Ref 'InstanceSecurityGroup']
      UserData:
        'Fn::Base64':
         !Sub |
          #!/bin/bash
            yum update -y
            yum install httpd -y
            service httpd start
            chkconfig httpd on
            cd /var/www/html
            echo "<html><h1>Arey Entra Edi</h1></html>" > index.html
      KeyName: !Ref 'KeyName'
      ImageId:  !FindInMap
        - AmazonLinuxAMI
        - !Ref 'AWS::Region'
        - AMI
  EC2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref 'InstanceType'
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      SecurityGroups: [!Ref 'InstanceSecurityGroup']
      UserData:
        'Fn::Base64':
         !Sub |
          #!/bin/bash
            yum update -y
            yum install httpd -y
            service httpd start
            chkconfig httpd on
            cd /var/www/html
            echo "<html><h1>Hello WeekEnd Batch... Welcome To AWS Classes</h1></html>" > index.html
      KeyName: !Ref 'KeyName'
      ImageId:  !FindInMap
        - AmazonLinuxAMI
        - !Ref 'AWS::Region'
        - AMI
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: !Ref 'SSHLocation'